feedreader/feedreader/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^feeds/', include('feeds.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

feedreader/feeds/urls.py
from django.conf.urls import url
from . import views


app_name = 'feeds'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<feed_id>[0-9]+)/$', views.FeedEntryList.as_view(), name='feed'),
    url(r'^addfeed/$', views.AddFeedView.as_view(), name='addfeed'),
    url(r'^author/$', views.AuthorView.as_view(), name='author'),
    url(r'^authorsearch/$', views.AuthorSearchView.as_view(), name='authorsearch'),
    url(r'^author/(?P<author_id>[0-9]+)/$', views.AuthorEntryList.as_view(), name='authorentries'),
]

feedreader/feeds/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.core.files.temp import NamedTemporaryFile
from django.core.files.images import ImageFile
from bs4 import BeautifulSoup
import urllib
import feedparser
import datetime


class Feed(models.Model):
    """The Feed class"""

    title = models.CharField(max_length=50, unique=True)
    url = models.URLField(max_length=200, unique=True)

    @classmethod
    def create(cls, title, url):
        """ Create a Feed object. """
        feed = cls(title=title, url=url)
        return feed

    @classmethod
    def save_feed_data(cls, url, title=None):
        """ Parse the feed and save it. """
        feed_parsed = feedparser.parse(url)
        if not title:
            # Used when submitting data through the command line tool
            try:
                feed = cls.objects.get(url=url)
            except cls.DoesNotExist:
                feed = cls.create(title=feed_parsed.feed.title,
                                  url=feed_parsed.href)
                feed.save()
        else:
            # Data verified by the FeedForm
            feed = cls.create(title=title, url=url)
            feed.save()

        return feed

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return HttpResponseRedirect(
            reverse('feeds:feed', kwargs={'feed_id': int(self.id)}))

    class Meta:
        ordering = ['title']


class Author(models.Model):
    """The Author class"""

    name = models.CharField(
        max_length=200, unique=True, null=True)

    @classmethod
    def create(cls, name):
        """ Create a Author object. """
        author = cls(name=name)
        return author

    @classmethod
    def save_author_data(cls, entry_parsed, entry_object):
        """ Parse the entry and save the authors. """
        if entry_parsed.has_key('authors'):
            # One or multiple authors
            for author in entry_parsed.authors:
                try:
                    new_author = cls.objects.get(name=author.name)
                except cls.DoesNotExist:
                    new_author = cls.create(name=author.name)
                    new_author.save()
                entry_object.authors.add(new_author)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return HttpResponseRedirect(
            reverse('feeds:authorentries', kwargs={'author_id': int(self.id)}))


class Entry(models.Model):
    """The Entry class"""

    title = models.CharField(max_length=100, unique=True)
    published = models.DateTimeField()
    url = models.URLField(max_length=200, unique=True)
    authors = models.ManyToManyField(Author)
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='entry_images/', null=True)
    image_url = models.URLField(max_length=200, null=True)

    @classmethod
    def create(cls, title, published, url, feed, image_url):
        """ Create a Entry object. """
        entry = cls(
            title=title, published=published, url=url, feed=feed,
            image_url=image_url)
        return entry

    @classmethod
    def save_entry_data(cls, feed, entry):
        """ Parse the entry and save it. """

        # Find an image and save its link
        try:
            soup = BeautifulSoup(entry.summary, 'html.parser')
            img_link = soup.find('img').get('src')
        except (urllib.error.URLError, AttributeError):
            # No img tag
            img_link = None

        try:
            # Entry already present, skip it
            new_entry = cls.objects.get(title=entry.title,
                                        url=entry.link)
            return
        except cls.DoesNotExist:
            # Create a new entry
            new_entry = cls.create(title=entry.title,
                published=datetime.datetime(*entry.published_parsed[:6]),
                url=entry.link, feed=feed, image_url=img_link)
            new_entry.save()

        # If there is an image, save it
        if img_link:
            img_temp = NamedTemporaryFile(delete=True)
            img_temp.write(urllib.request.urlopen(img_link).read())
            img_temp.flush()
            new_entry.image.save('entry_{0}'.format(new_entry.id),
                                 ImageFile(img_temp))

        return new_entry

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-published']

feedreader/feeds/forms.py
from django import forms
from django.utils.translation import ugettext, ugettext_lazy as _
import feedparser
from . import models


class FeedForm(forms.ModelForm):

    error_messages = {
        'not_RSS': _("The provided URL is not a valid RSS feed."),
    }

    class Meta:
        model = models.Feed
        fields = ('title', 'url')

        labels = {
            'url': _('URL'),
        }

        help_texts = {
            'title': 'Enter a unique title for the RSS feed',
            'url': 'Enter a unique URL for the RSS feed'
        }

    def clean(self):
        """ An overriden clean method that tests the validity of the
            provided URL. """
        cleaned_data = super(FeedForm, self).clean()
        if not self.is_valid():
            raise forms.ValidationError(
                self.error_messages['not_RSS'], code='not_RSS')
        feed = feedparser.parse(cleaned_data['url'])
        if 'rss' not in feed.version.lower():
            raise forms.ValidationError(
                self.error_messages['not_RSS'], code='not_RSS')

        return cleaned_data


class AuthorForm(forms.Form):

    error_messages = {
        'no_author': _('No author was found under this name.'),
        'no_name': _('Please type the name of the author'),
    }

    name = forms.CharField(
        max_length=200, label="Author's name",
        help_text="Enter the author's name", strip=True)

    def clean(self):
        """ An overriden clean method that test the existence of an author. """
        if not self.is_valid():
            raise forms.ValidationError(
                self.error_messages['no_name'], code='no_name')

        cleaned_data = super(AuthorForm, self).clean()
        try:
            author = models.Author.objects.filter(
                name__contains=cleaned_data['name'])
            if author.count() == 0:
                raise models.Author.DoesNotExist
        except models.Author.DoesNotExist:
            raise forms.ValidationError(
                self.error_messages['no_author'], code='no_author')

feedreader/feeds/views.py
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
import feedparser
import json
from . import models
from . import forms


class IndexView(generic.ListView):
    """ The IndexView class.
        Displays lists of feeds and entries. """

    template_name = 'feeds/index.html'
    context_object_name = 'list_entries'
    model = models.Entry
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['list_feeds'] = models.Feed.objects.all()
        return context


class FeedEntryList(generic.ListView):
    """ The FeedEntryList class.
        Displays a list of entries for a particular feed. """

    template_name = 'feeds/feed_list.html'
    context_object_name = 'list_entries'
    model = models.Entry
    paginate_by = 20

    def get_queryset(self):
        self.feed = get_object_or_404(models.Feed, id=self.kwargs['feed_id'])
        return models.Entry.objects.filter(feed=self.feed)

    def get_context_data(self, **kwargs):
        context = super(FeedEntryList, self).get_context_data(**kwargs)
        context['feed'] = self.feed
        context['list_feeds'] = models.Feed.objects.all()
        return context


class AddFeedView(generic.CreateView):
    """ The AddFeedView class.
        Used for adding new feeds. """

    template_name = 'feeds/add_feed.html'
    form_class = forms.FeedForm
    model = models.Feed

    def form_valid(self, form):
        # Extract data from the form
        data = form.cleaned_data
        # Parse feed
        feed_parsed = feedparser.parse(data['url'])
        # Create a Feed object
        feed = models.Feed.save_feed_data(title=data['title'], url=data['url'])

        for entry in feed_parsed.entries:
            entry_object = models.Entry.save_entry_data(entry=entry, feed=feed)
            if not entry_object:
                # Entry already present, skip it
                continue
            # Add authors to entries
            author_object = models.Author.save_author_data(
                entry_parsed=entry, entry_object=entry_object)

        return feed.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super(AddFeedView, self).get_context_data(**kwargs)
        context['list_feeds'] = models.Feed.objects.all()
        return context


class AuthorEntryList(generic.ListView):
    """ The AuthorEntryList class.
        Displays a list of entries of a particular author. """

    template_name = 'feeds/author_entry_list.html'
    context_object_name = 'list_entries'
    model = models.Entry
    paginate_by = 20

    def get_queryset(self):
        self.author = get_object_or_404(
            models.Author, id=self.kwargs['author_id'])
        return models.Entry.objects.filter(authors=self.author)

    def get_context_data(self, **kwargs):
        context = super(AuthorEntryList, self).get_context_data(**kwargs)
        context['author'] = self.author
        context['list_feeds'] = models.Feed.objects.all()
        return context


class AuthorView(generic.FormView):
    """ The AuthorView class.
        Used for rendering the author search form and redirecting to the
        AuthorEntryList upon a successful search. """

    template_name = 'feeds/author_search.html'
    form_class = forms.AuthorForm
    model = models.Author

    def form_valid(self, form):
        data = form.cleaned_data
        author = models.Author.objects.get(name__contains=data['name'])
        return author.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super(AuthorView, self).get_context_data(**kwargs)
        context['list_feeds'] = models.Feed.objects.all()
        return context


class AuthorSearchView(generic.FormView):
    """ The AuthorSearchView class.
        Used for sending a list of possible authors as JSON after receiving at
        least two letters. """

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            cleaned_data = []
            search_term = request.GET['term']
            query_results = models.Author.objects.filter(
                name__contains=search_term)
            for result in query_results:
                result_json = {}
                result_json['id'] = result.id
                result_json['label'] = result.name
                result_json['value'] = result.name
                cleaned_data.append(result_json)
            json_data = json.dumps(cleaned_data)
            return HttpResponse(json_data, 'application/json')

feedreader/feeds/templates/feeds/add_feed.html
{% extends "feeds/base.html" %}

{% block title %}
  FeedReader - Add
{% endblock title %}

{% block content %}
  <form action="{% url "feeds:addfeed" %}" method="post" class="form-horizontal">
    {% csrf_token %}
    {% include "feeds/form_snippet.html" %}
    <div class="form-group">
      <input type="submit" class="btn btn-default" value="Save" />
    </div>
  </form>
{% endblock content %}

{% block sidebar %}
  {% include "feeds/feeds_snippet.html" with list_feeds=list_feeds %}
{% endblock sidebar %}

feedreader/feeds/templates/feeds/author_entry_list.html
{% extends "feeds/base.html" %}

{% block title %}
  FeedReader - {{ author.name }}
{% endblock title %}

{% block content %}
<div class="page-header">
  <h1>Author <small>{{ author.name }}</small></h1>
</div>
{% comment %}
    List entries for the specified feed
    {% endcomment %}
    {% include "feeds/entries_snippet.html" with page_obj=page_obj %}
{% comment %}
  Pagination
  {% endcomment %}
  {% include "feeds/pagination_snippet.html" with page_obj=page_obj%}
{% endblock content %}

{% block sidebar %}
  {% include "feeds/feeds_snippet.html" with list_feeds=list_feeds %}
{% endblock sidebar %}

feedreader/feeds/templates/feeds/author_search.html
{% extends "feeds/base.html" %}

{% block title %}
  FeedReader - Search
{% endblock title %}

{% block content %}
  <div class="ui-widget">
    <form action="{% url "feeds:author" %}" method="post" class="form-horizontal">
      {% csrf_token %}
      {% include "feeds/form_snippet.html" %}
      <div class="form-group">
        <input type="submit" class="btn btn-default" value="Search" />
      </div>
    </form>
  </div>
{% endblock content %}

{% block sidebar %}
  {% include "feeds/feeds_snippet.html" with list_feeds=list_feeds %}
{% endblock sidebar %}

{% block js %}
  <script type="text/javascript">
    $(function() {
      $("#id_name").autocomplete({
        source: "{% url "feeds:authorsearch" %}",
        minLength: 2,
        delay: 200,
      });
    });
  </script>
{% endblock js %}

feedreader/feeds/templates/feeds/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <title>{% block title %}FeedReader{% endblock title %}</title>
  <meta name="generator" content="FeedReader" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" media="screen" charset="utf-8">
  <link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}" media="screen" charset="utf-8">
  <link rel="stylesheet" href="{% static "css/jquery-ui.min.css" %}" media="screen" charset="utf-8">
  <link rel="stylesheet" href="{% static "css/jquery-ui.structure.min.css" %}" media="screen" charset="utf-8">
  <link rel="stylesheet" href="{% static "css/jquery-ui.theme.min.css" %}" media="screen" charset="utf-8">
</head>
<body>

  <header class="navbar navbar-default navbar-static-top" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="{% url "feeds:index" %}" class="navbar-brand">FeedReader</a>
      </div>
      <nav class="collapse navbar-collapse" role="navigation">
        <ul class="nav navbar-nav">
          <li>
            <a href="{% url "feeds:addfeed" %}">Add feed</a>
          </li>
          <li>
            <a href="{% url "feeds:author" %}">Search by author</a>
          </li>
        </ul>
      </nav>
    </div>
  </header>

  <!-- Begin Body -->
  <div class="container">
  <div class="row">
      <div class="col-md-9">
        {% comment %}
          A block for adding entries
        {% endcomment %}
        {% block content %}
        {% endblock content %}
      </div>
      <div class="col-md-3" id="rightCol">
        <div class="well">
          <ul class="nav nav-stacked" id="sidebar">
            {% comment %}
              A block for adding feeds
            {% endcomment %}
            {% block sidebar %}
            {% endblock sidebar %}
          </ul>
        </div>

      </div>
    </div>
  </div>

  <!-- script references -->
  {% load staticfiles %}
  <script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/jquery-ui.min.js" %}"></script>
  {% block js %}
  {% endblock js %}
</body>
</html>

feedreader/feeds/templates/feeds/entries_snippet.html
<ul>
  {% for entry in page_obj %}
  <div class="media well well-sm">
    {% if entry.image %}
      {% include "feeds/thumbnails_snippet.html" with entry=entry%}
    {% endif %}
    <div class="media-body">
      <h4 class="media-heading"><a target="_blank" href="{{ entry.url }}">{{ entry.title }}</a></h4>
      <p class="text-muted">
        {% if entry.authors.all %}
          {% for author in entry.authors.all %}
            {% if entry.authors.all|length == 1 %}
               Written by: {{ author.name }}
            {% else %}
               Written by: {{ author.name }},
            {% endif %}
          {% endfor %}
        {% endif %}
      </p>
      <p class="text-muted">Published on: {{ entry.published }}</p>
    </div>
  </div>
  {% endfor %}
</ul>

feedreader/feeds/templates/feeds/feed_list.html
{% extends "feeds/base.html" %}

{% block title %}
  FeedReader - {{ feed.title }}
{% endblock title %}

{% block content %}
<div class="page-header">
  <h1>Feed <small><a target="_blank" href="{{ feed.url }}">{{ feed.title }}</a></small></h1>
</div>
{% comment %}
    List entries for the specified feed
    {% endcomment %}
    {% include "feeds/entries_snippet.html" with page_obj=page_obj %}
{% comment %}
  Pagination
  {% endcomment %}
  {% include "feeds/pagination_snippet.html" with page_obj=page_obj%}
{% endblock content %}

{% block sidebar %}
  {% include "feeds/feeds_snippet.html" with list_feeds=list_feeds %}
{% endblock sidebar %}

feedreader/feeds/templates/feeds/feeds_snippet.html
{% for feed in list_feeds %}
  <li><a href="{% url "feeds:feed" feed.id %}">{{ feed.title }}</a></li>
{% endfor %}

feedreader/feeds/templates/feeds/form_snippet.html
{% if form.errors %}
  <div class="alert alert-danger">
    {% for error in form.non_field_errors %}
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {% if field.errors %}
      <div class="alert alert-warning">
      {% for error in form.non_field_errors %}
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> {{ error }}
      {% endfor %}
      </div>
    {% endif %}
    <div>
      {{ field.label_tag }}
    </div>
    <div>
      {{ field }}
    </div>
    {% if field.help_text %}
      <span id="helpBlock" class="help help-block">{{ field.help_text|safe }}</span>
    {% endif %}
  </div>

{% endfor %}

{% for field in form.hidden_fields %}
  {{ field }}
{% endfor %}

feedreader/feeds/templates/feeds/index.html
{% extends "feeds/base.html" %}

{% block content %}
{% comment %}
  List all entries
{% endcomment %}
<div>
  {% include "feeds/entries_snippet.html" with page_obj=list_entries %}
</div>
{% comment %}
  Pagination
{% endcomment %}
{% if is_paginated %}
  {% include "feeds/pagination_snippet.html" with page_obj=page_obj%}
{% endif %}
{% endblock content %}


{% block sidebar %}
  {% include "feeds/feeds_snippet.html" with list_feeds=list_feeds %}
{% endblock sidebar %}

feedreader/feeds/templates/feeds/pagination_snippet.html
<div align="center">
  <nav>
    <ul class="pagination pagination-lg">
        {% if page_obj.has_previous %}
        <li>
          <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% endif %}

        <li>
          <span class="current">Page {{ page_obj.number }} of {{ paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
        <li>
          <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        {% endif %}
    </ul>
  </nav>
</div>

feedreader/feeds/templates/feeds/thumbnails_snippet.html
<div class="media-left">
  {% load thumbnail %}
  {% thumbnail entry.image "100x50" crop="center" as im %}
    <a href="#"><img src="{{ im.url }}" class="media-object img-rounded" data-holder-rendered="true"></a>
  {% endthumbnail %}
</div>